gnome-terminal -x sh -c "roslaunch freenect_launch freenect.launch"
read -p "Press [Enter] to start...................."
gnome-terminal -x sh -c "roslaunch rtabmap_ros apli.launch rtabmap_args:="--delete_db_on_start""
read -p "Press [Enter] to start...................."
gnome-terminal -x sh -c "rosrun depthimage_to_laserscan depthimage_to_laserscan image:=/camera/depth/image_raw"
gnome-terminal -x sh -c "rosrun crab_tf tf_base_camera"
read -p "Press [Enter] to start...................."
gnome-terminal -x sh -c "rosrun crab_tf tf_brcast"
read -p "Press [Enter] to start...................."
gnome-terminal -x sh -c "rosrun rviz rviz"
read -p "Press [Enter] to start...................."
gnome-terminal -x sh -c "rosrun gmapping slam_gmapping scan:=/scan"
gnome-terminal -x sh -c "rosrun roboteq sub"
